services:
    cmcontentbirdconnector.controller_api:
        class: creemedia\Bundle\eZcontentbirdBundle\Controller\ContentBirdApiController
        arguments: ['@service_container', '@ezpublish.api.repository']
    cmcontentbirdconnector.service.api:
        class: creemedia\Bundle\eZcontentbirdBundle\Common\ContentBirdApiService
        arguments: ['@service_container', '@ezpublish.api.repository']

    cmcontentbirdconnector.service.cms:
        class: creemedia\Bundle\eZcontentbirdBundle\Common\CmsService
        arguments: ['@service_container', '@ezpublish.api.repository']

    cmcontentbirdconnector.service.mover:
        class: creemedia\Bundle\eZcontentbirdBundle\Common\ContentMoverService
        arguments: ['@service_container', '@ezpublish.api.repository']

    cmcontentbirdconnector.service.parser:
        class: creemedia\Bundle\eZcontentbirdBundle\Common\ContentParserService
        arguments: ['@service_container']

    cmcontentbirdconnector.onpublish_slot:
        class: creemedia\Bundle\eZcontentbirdBundle\Slot\OnPublishSlot
        arguments: ['@ezpublish.api.service.content', '@service_container']
        tags:
            - { name: ezpublish.api.slot, signal: ContentService\PublishVersionSignal }

    cmcontentbirdconnector.ondelete_slot:
        class: creemedia\Bundle\eZcontentbirdBundle\Slot\OnDeleteSlot
        arguments: ['@ezpublish.api.service.content', '@service_container']
        tags:
            - { name: ezpublish.api.slot, signal: ContentService\DeleteVersionSignal }
